models/Objetos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "objetos".
 *
 * @property int $id_objeto
 * @property string $nombre
 * @property string|null $imagen
 * @property string|null $descripcion
 * @property string $tipo
 * @property int $mágico
 * @property int|null $oro
 *
 * @property Objetosdelpersonaje[] $objetosdelpersonajes
 * @property Personajes[] $personajes
 * @property Recomobjetos[] $recomobjetos
 * @property Usuarios[] $usuarios
 */
class Objetos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'objetos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'tipo'], 'required'],
            [['descripcion'], 'string'],
            [['mágico', 'oro', 'plata', 'cobre'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['tipo'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_objeto' => 'Id Objeto',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripción',
            'tipo' => 'Tipo',
            'mágico' => 'Mágico',
            'oro' => 'Oro',
            'plata' => 'Plata',
            'cobre' => 'Cobre',
        ];
    }

    /**
     * Gets query for [[Objetosdelpersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getObjetosdelpersonajes()
    {
        return $this->hasMany(Objetosdelpersonaje::className(), ['id_objeto' => 'id_objeto']);
    }

    /**
     * Gets query for [[Personajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPersonajes()
    {
        return $this->hasMany(Personajes::className(), ['id_personaje' => 'id_personaje'])->viaTable('objetosdelpersonaje', ['id_objeto' => 'id_objeto']);
    }

    /**
     * Gets query for [[Recomobjetos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRecomobjetos()
    {
        return $this->hasMany(Recomobjetos::className(), ['id_objeto' => 'id_objeto']);
    }

    /**
     * Gets query for [[Usuarios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarios()
    {
        return $this->hasMany(Usuarios::className(), ['id_usuario' => 'id_usuario'])->viaTable('recomobjetos', ['id_objeto' => 'id_objeto']);
    }
}

controllers/ObjetosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Objetos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ObjetosController implements the CRUD actions for Objetos model.
 */
class ObjetosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Objetos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Objetos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Objetos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Objetos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Objetos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_objeto]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Objetos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_objeto]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Objetos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['listaobjetos']);
    }

    /**
     * Finds the Objetos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Objetos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Objetos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionListaobjetos(){
        $dataProvider = new ActiveDataProvider([
            'query' => Objetos::find(),
        ]);
        
        return $this->render('objetos',[
            'dataProvider' => $dataProvider,
        ]);
    }
}

views/objetos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Objetos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="objetos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'tipo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mágico')->checkbox() ?>

    <?= $form->field($model, 'oro')->textInput() ?>
    
    <?= $form->field($model, 'plata')->textInput() ?>
    
    <?= $form->field($model, 'cobre')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/objetos/_objetos.php
<?php
use yii\helpers\Html;

?>

<div class="col-sm-4">
    <div class="thumbnail objetos">
        
            <h3><u><?= $model->nombre ?></u></h3>
            <p> </p>
            <h5>
                <?= $model->descripcion ?>
            
            </h5>
            <p> </p>
            <h5><b>Tipo de objeto:</b> <?= $model->tipo ?></h5>
            <?php if ($model->mágico): ?>
                <h5><b>Mágico:</b>
                    <font color="green">Si</font>
                </h5>
            <?php else: ?>
                <h5><b>Mágico:</b>
                    <font color="red">No</font>
                </h5>
            <?php endif; ?>
            <p><b>Valor:</b> 
                <?= $model->oro ?> <?= Html::img('@web/images/moneda-oro.png', ['class' => 'iconos'], ['alt' => 'moneda de oro']); ?>
                <?= $model->plata ?> <?= Html::img('@web/images/moneda-plata.png', ['class' => 'iconos'], ['alt' => 'moneda de plata']); ?>
                <?= $model->cobre ?> <?= Html::img('@web/images/moneda-cobre.png', ['class' => 'iconos'], ['alt' => 'moneda de cobre']); ?>
            </p>

    </div>
</div>

views/objetos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Objetos */

$this->title = 'Añadir objeto';
$this->params['breadcrumbs'][] = ['label' => 'Objetos', 'url' => ['objetos/listaobjetos']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="objetos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/objetos/objetos.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ListView;
    use yii\grid\GridView;
    
    $this->title = 'Objetos';
    $this->params['breadcrumbs'][] = $this->title;
?>
<?php if(Yii::$app->user->isGuest): ?>

<div class="view">
    
    <div class="well well-lg"><h2 style="text-align: center">
        <?= Html::img('@web/images/poción.png', ['class' => 'iconosheader'], ['alt' => 'espada']); ?> 
            Objetos
        <?= Html::img('@web/images/poción.png', ['class' => 'iconosheader'], ['alt' => 'espada']); ?> 
        </h2>
    </div>
    
    <div class="recordatorio">
        <div class="recordatorio-texto">
        <h4>Recordatorio:</h4>
        <h5>1 <?= Html::img('@web/images/moneda-oro.png', ['class' => 'iconos'], ['alt' => 'moneda de oro']); ?> 
            = 10 <?= Html::img('@web/images/moneda-plata.png', ['class' => 'iconos'], ['alt' => 'moneda de plata']); ?></h5>
        <h5>1 <?= Html::img('@web/images/moneda-plata.png', ['class' => 'iconos'], ['alt' => 'moneda de plata']); ?> 
            = 10 <?= Html::img('@web/images/moneda-cobre.png', ['class' => 'iconos'], ['alt' => 'moneda de cobre']); ?></h5>
        </div>
    </div>
    
    <?= ListView::widget([
               'dataProvider' => $dataProvider,
               'itemView' => '_objetos',
               'layout' => "\n{pager}\n{items}",
            ]);
     ?>       
</div>

<?php else: ?>

<div class="objetos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Añadir Objetos', ['create'], ['class' => 'btn btn-default']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            
            ['class' => 'yii\grid\ActionColumn'],
            
            'nombre',
            'descripcion:ntext',
            'tipo',
            [
                    'attribute' => 'mágico',
                    'label'=>'¿Arma Mágica?',
                    'format'=>'raw',
                    'value' => function($model) { return $model->mágico == 0 ? 'No' : 'Sí';},
            ],
            'oro',
            'plata',
            'cobre',

            
        ],
    ]); ?>


</div>


<?php endif; ?>

views/objetos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Objetos */

$this->title = 'Modificar objeto: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Objetos', 'url' => ['objetos/listaobjetos']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id_objeto]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="objetos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/objetos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Objetos */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Objetos', 'url' => ['objetos/listaobjetos']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="objetos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id_objeto], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id_objeto], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estás seguro?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nombre',
            'descripcion:ntext',
            'tipo',
            [
                    'attribute' => 'mágico',
                    'label'=>'¿Arma Mágica?',
                    'format'=>'raw',
                    'value' => function($model) { return $model->mágico == 0 ? 'No' : 'Sí';},
            ],
            'oro',
            'plata',
            'cobre',
        ],
    ]) ?>

</div>