models/Personajes.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "personajes".
 *
 * @property int $id_personaje
 * @property int|null $id_usuario
 * @property int|null $id_armadura
 * @property int|null $id_raza
 * @property int|null $id_trasfondo
 * @property string $nombre
 * @property string|null $descripción
 * @property string|null $imagen
 * @property int $vivo
 * @property string|null $biografia
 * @property int $edad
 * @property int $nivel
 * @property string|null $alineamineto
 * @property int $fuerza
 * @property int $destreza
 * @property int $constitucion
 * @property int $inteligencia
 * @property int $sabiduria
 * @property int $carisma
 * @property int|null $modfuerza
 * @property int|null $moddestreza
 * @property int|null $modconstitucion
 * @property int|null $modinteligencia
 * @property int|null $modsabiduria
 * @property int|null $modcarisma
 * @property int|null $vida
 * @property int|null $iniciativa
 * @property int|null $inspiracion
 * @property int|null $ca
 * @property int $escudo
 * @property int|null $oro
 * @property int|null $plata
 * @property int|null $cobre
 * @property int|null $velocidad
 * @property int|null $salvfuerza
 * @property int|null $salvdestreza
 * @property int|null $salvconstitucion
 * @property int|null $salvinteligencia
 * @property int|null $salvsabiduria
 * @property int|null $salvcarisma
 * @property int|null $bono_competencia
 * @property int|null $acrobacias
 * @property int|null $atletismo
 * @property int|null $conoarcano
 * @property int|null $engaño
 * @property int|null $historia
 * @property int|null $interpretacion
 * @property int|null $intimidacion
 * @property int|null $investigacion
 * @property int|null $juego_de_manos
 * @property int|null $medicina
 * @property int|null $naturaleza
 * @property int|null $percepcion
 * @property int|null $perspicacia
 * @property int|null $persuasión
 * @property int|null $religion
 * @property int|null $sigilo
 * @property int|null $supervivencia
 * @property int|null $trato_animales
 * @property int|null $percepción_pasiva
 * @property int|null $salv_conjuto
 * @property int|null $mod_ataque_conjuro
 * @property string|null $notas
 * @property int|null $recomendado
 *
 * @property Armaspersonaje[] $armaspersonajes
 * @property Armas[] $armas
 * @property Clasesdelospersonajes[] $clasesdelospersonajes
 * @property Clases[] $clases
 * @property Dotesdelospersonajes[] $dotesdelospersonajes
 * @property Dotes[] $dotes
 * @property Idiomaspersonaje[] $idiomaspersonajes
 * @property Magiaspersonajes[] $magiaspersonajes
 * @property Magias[] $magias
 * @property Objetosdelpersonaje[] $objetosdelpersonajes
 * @property Objetos[] $objetos
 * @property Armaduras $armadura
 * @property Razas $raza
 * @property Trasfondos $trasfondo
 * @property Usuarios $usuario
 * @property Personajesesion[] $personajesesions
 * @property Sesiones[] $sesions
 */
class Personajes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'personajes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_usuario', 'id_armadura', 'id_raza', 'id_trasfondo', 'vivo', 'edad', 'fuerza', 'destreza', 'constitucion', 'inteligencia', 'sabiduria', 'carisma', 'modfuerza', 'moddestreza', 'modconstitucion', 'modinteligencia', 'modsabiduria', 'modcarisma', 'vida', 'iniciativa', 'inspiracion', 'ca', 'escudo', 'oro', 'plata', 'cobre', 'velocidad', 'salvfuerza', 'salvdestreza', 'salvconstitucion', 'salvinteligencia', 'salvsabiduria', 'salvcarisma', 'bono_competencia', 'acrobacias', 'atletismo', 'conoarcano', 'engaño', 'historia', 'interpretacion', 'intimidacion', 'investigacion', 'juego_de_manos', 'medicina', 'naturaleza', 'percepcion', 'perspicacia', 'persuasión', 'religion', 'sigilo', 'supervivencia', 'trato_animales', 'percepción_pasiva', 'salv_conjuto', 'mod_ataque_conjuro', 'recomendado'], 'integer'],
            [['nivel'], 'integer', 'min'=>1,'max'=>20],
            [['nombre', 'edad', 'fuerza', 'destreza', 'constitucion', 'inteligencia', 'sabiduria', 'carisma'], 'required'],
            [['fuerza', 'destreza', 'constitucion', 'inteligencia', 'sabiduria', 'carisma'],'integer', 'min'=>1,'max'=>20,],
            [['descripción', 'biografia', 'alineamineto', 'notas'], 'string'],
            [['nombre'], 'string', 'max' => 100],
            [['id_armadura'], 'exist', 'skipOnError' => true, 'targetClass' => Armaduras::className(), 'targetAttribute' => ['id_armadura' => 'id_armaduras']],
            [['id_raza'], 'exist', 'skipOnError' => true, 'targetClass' => Razas::className(), 'targetAttribute' => ['id_raza' => 'id_raza']],
            [['id_trasfondo'], 'exist', 'skipOnError' => true, 'targetClass' => Trasfondos::className(), 'targetAttribute' => ['id_trasfondo' => 'id_trasfondo']],
            [['id_usuario'], 'exist', 'skipOnError' => true, 'targetClass' => Usuarios::className(), 'targetAttribute' => ['id_usuario' => 'id_usuario']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_personaje' => 'Id Personaje',
            'id_usuario' => 'Usuario',
            'id_armadura' => 'Armadura',
            'id_raza' => 'Raza',
            'id_trasfondo' => 'Trasfondo',
            'nombre' => 'Nombre',
            'descripción' => 'Descripción',
            'vivo' => 'Vivo',
            'biografia' => 'Biografía',
            'edad' => 'Edad',
            'nivel' => 'Nivel',
            'alineamineto' => 'Alineamineto',
            'fuerza' => 'Fuerza',
            'destreza' => 'Destreza',
            'constitucion' => 'Constitucion',
            'inteligencia' => 'Inteligencia',
            'sabiduria' => 'Sabiduria',
            'carisma' => 'Carisma',
            'modfuerza' => 'Modificar de fuerza',
            'moddestreza' => 'Modificador de destreza',
            'modconstitucion' => 'Modificador de constitución',
            'modinteligencia' => 'Modificador de inteligencia',
            'modsabiduria' => 'Modificador de sabiduria',
            'modcarisma' => 'Modificador de carisma',
            'vida' => 'Vida',
            'iniciativa' => 'Iniciativa',
            'inspiracion' => 'Inspiracion',
            'ca' => 'Clase de Armadura',
            'escudo' => 'Escudo',
            'oro' => 'Oro',
            'plata' => 'Plata',
            'cobre' => 'Cobre',
            'velocidad' => 'Velocidad',
            'salvfuerza' => 'Salvación de fuerza',
            'salvdestreza' => 'Salvación de destreza',
            'salvconstitucion' => 'Salvación de constitución',
            'salvinteligencia' => 'Salvación de inteligencia',
            'salvsabiduria' => 'Salvación de sabiduría',
            'salvcarisma' => 'Salvación de carisma',
            'bono_competencia' => 'Bono por Competencia',
            'acrobacias' => 'Acrobacias',
            'atletismo' => 'Atletismo',
            'conoarcano' => 'Conocimiento Arcano',
            'engaño' => 'Engaño',
            'historia' => 'Historia',
            'interpretacion' => 'Interpretación',
            'intimidacion' => 'Intimidación',
            'investigacion' => 'Investigacion',
            'juego_de_manos' => 'Juego De Manos',
            'medicina' => 'Medicina',
            'naturaleza' => 'Naturaleza',
            'percepcion' => 'Percepción',
            'perspicacia' => 'Perspicacia',
            'persuasión' => 'Persuasión',
            'religion' => 'Religión',
            'sigilo' => 'Sigilo',
            'supervivencia' => 'Supervivencia',
            'trato_animales' => 'Trato con Animales',
            'percepción_pasiva' => 'Percepción Pasiva',
            'salv_conjuto' => 'Salvación de Conjuro',
            'mod_ataque_conjuro' => 'Modificador de Ataque Conjuro',
            'notas' => 'Notas',
            'recomendado' => 'Recomendado',
        ];
    }

    /**
     * Gets query for [[Armaspersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArmaspersonajes()
    {
        return $this->hasMany(Armaspersonaje::className(), ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Armas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getArmas()
    {
        return $this->hasMany(Armas::className(), ['id_arma' => 'id_arma'])->viaTable('armaspersonaje', ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Clasesdelospersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getClasesdelospersonajes()
    {
        return $this->hasMany(Clasesdelospersonajes::className(), ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Clases]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getClases()
    {
        return $this->hasMany(Clases::className(), ['id_clase' => 'id_clase'])->viaTable('clasesdelospersonajes', ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Dotesdelospersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDotesdelospersonajes()
    {
        return $this->hasMany(Dotesdelospersonajes::className(), ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Dotes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDotes()
    {
        return $this->hasMany(Dotes::className(), ['id_dote' => 'id_dote'])->viaTable('dotesdelospersonajes', ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Idiomaspersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdiomaspersonajes()
    {
        return $this->hasMany(Idiomaspersonaje::className(), ['id_personaje' => 'id_personaje']);
    }

    /**
     * Gets query for [[Magiaspersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */

controllers/PersonajesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Personajes;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PersonajesController implements the CRUD actions for Personajes model.
 */
class PersonajesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Personajes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Personajes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Personajes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Personajes();
        $modelUsuario = \app\models\Usuarios::find()->all();
        $modelArmadura = \app\models\Armaduras::find()->all();
        $modelRaza = \app\models\Razas::find()->all();
        $modelTrasfondo = \app\models\Trasfondos::find()->all();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_personaje]);
        }

        return $this->render('create', [
            'model' => $model,
            'modelUsuario' => $modelUsuario,
            'modelArmadura' => $modelArmadura,
            'modelRaza' => $modelRaza,
            'modelTrasfondo' => $modelTrasfondo,
        ]);
    }
    public function actionCreatepersonajepasos()
    {
        $model = new Personajes();
        $modelUsuario = \app\models\Usuarios::find()->all();
        $modelArmadura = \app\models\Armaduras::find()->all();
        $modelRaza = \app\models\Razas::find()->all();
        $modelTrasfondo = \app\models\Trasfondos::find()->all();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['clasesdelospersonajes/create', 'id_personaje' => $model->id_personaje]);
        }
         if (Yii::$app->request->isPost) {
                $model->imagen = UploadedFile::getInstance($model, 'imagen');
                if ($model->imagen = UploadedFile::getInstance($model, 'imagen')) {
                    
                    if ($model->validate()) {
                        $model->imagen->saveAs('../web/img/' . $model->nombre . '.' . $model->imagen->extension);
                    }
                }
            }
        return $this->render('create', [
            'model' => $model,
            'modelUsuario' => $modelUsuario,
            'modelArmadura' => $modelArmadura,
            'modelRaza' => $modelRaza,
            'modelTrasfondo' => $modelTrasfondo,
        ]);
    }

    /**
     * Updates an existing Personajes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelUsuario = \app\models\Usuarios::find()->all();
        $modelArmadura = \app\models\Armaduras::find()->all();
        $modelRaza = \app\models\Razas::find()->all();
        $modelTrasfondo = \app\models\Trasfondos::find()->all();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_personaje]);
        }

        return $this->render('update', [
            'model' => $model,
            'modelUsuario' => $modelUsuario,
            'modelArmadura' => $modelArmadura,
            'modelRaza' => $modelRaza,
            'modelTrasfondo' => $modelTrasfondo,
        ]);
    }

    /**
     * Deletes an existing Personajes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['listapersonajes']);
    }

    /**
     * Finds the Personajes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Personajes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Personajes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionListapersonajes(){
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find(),
        ]);
                
        return $this->render("personajes", [
             'dataProvider' => $dataProvider,
        ]);
    }
    
        public function actionListapersonajesusuarios($id_usuario){
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where("id_usuario = $id_usuario"),
        ]);
                
        return $this->render("personajes", [
             'dataProvider' => $dataProvider,
        ]);
    }
    public function actionPersonajesrecomendados(){
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where("recomendado = True"),
        ]);
                
        return $this->render("personajes", [
             'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionPersonajesnorecomendados(){
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where("recomendado = False"),
        ]);
                
        return $this->render("personajes", [
             'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionPersonaje($id){
        $dataProvider = new ActiveDataProvider([
            'query' => Personajes::find()->where("id_personaje = $id"),
        ]);
                
        return $this->render("personajecompleto", [
             'dataProvider' => $dataProvider,
        ]);
    }
   
}

views/personajes/_formcrear.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\models\Personajes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="personajes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php $modelUsuario = ArrayHelper::map($modelUsuario, 'id_usuario', 'nombre'); ?>
    <?php $modelRaza = ArrayHelper::map($modelRaza, 'id_raza', 'nombre'); ?>
    <?php $modelArmadura = ArrayHelper::map($modelArmadura, 'id_armaduras', 'nombre'); ?>
    <?php $modelTrasfondo = ArrayHelper::map($modelTrasfondo, 'id_trasfondo', 'nombre'); ?>
    
    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'id_raza')->dropDownList($modelRaza,['prompt' => ''])->label('Razas') ?>

    <?= $form->field($model, 'id_armadura')->dropDownList($modelArmadura,['prompt' => ''])->label('Armaduras') ?>

    <?= $form->field($model, 'id_trasfondo')->dropDownList($modelTrasfondo,['prompt' => ''])->label('Trasfondo') ?>
    
    <?= $form->field($model, 'id_usuario')->dropDownList($modelUsuario,['prompt' => ''])->label('Usuarios') ?>

    <?= $form->field($model, 'imagen')->textInput()->label('Introduzca la ruta de la imagen') ?>

    <?= $form->field($model, 'biografia')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'edad')->textInput() ?>

    <?= $form->field($model, 'nivel')->textInput() ?>

    <?= $form->field($model, 'alineamineto')->dropDownList([ 'Legal bueno' => 'Legal bueno', 'Neutral bueno' => 'Neutral bueno', 'Caótico bueno' => 'Caótico bueno', 'Legal neutral' => 'Legal neutral', 'Neutral' => 'Neutral', 'Caótico neutral' => 'Caótico neutral', 'Legal malvado' => 'Legal malvado', 'Neutral malvado' => 'Neutral malvado', 'Caótico malvado' => 'Caótico malvado', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'fuerza')->textInput() ?>

    <?= $form->field($model, 'destreza')->textInput() ?>

    <?= $form->field($model, 'constitucion')->textInput() ?>

    <?= $form->field($model, 'inteligencia')->textInput() ?>

    <?= $form->field($model, 'sabiduria')->textInput() ?>

    <?= $form->field($model, 'carisma')->textInput() ?>

    <?= $form->field($model, 'vida')->textInput() ?>

    <?= $form->field($model, 'inspiracion')->checkbox() ?>

    <?= $form->field($model, 'escudo')->checkbox() ?> 
    

    <div class="form-group">
        <?= Html::submitButton('Siguiente', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/personajes/_personajes.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

?>

<div class="col-sm-6 col-md-3">
    <div class="thumbnail personajes">
        
            <?php if ($model->imagen): ?>
            <img src="<?=$model->imagen?>" alt="imagenes de los personajes" class='imagenespersonajesyusuarios'>
             <?php else: ?>
                <?= Html::img('@web/images/imagen_prueba.png', ['alt' => 'imagenes por defecto'], ['class' => 'imagenespersonajesyusuarios ']) ?>               
             <?php endif; ?>
            <h2><?= $model->nombre?></h2>
            <h3><?= $model->raza->nombre ?></h3>
            <h3><?= implode('</h3><h3>', ArrayHelper::getColumn($model->clases, 'nombre'))?></h3>
            <h3> Nivel total: <?= $model->nivel?></h3>
            <h2><?= $model->usuario->nombre ?></h2>
            <p><?= Html::a('Toda la información', ['personajes/view', 'id' => $model->id_personaje], ['class' => 'btn btn-default']) ?></p>
        
    </div>
</div>

views/personajes/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Personajes */

$this->title = 'Añadir Personaje';
$this->params['breadcrumbs'][] = ['label' => 'Personajes', 'url' => ['personajes/listapersonajes']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="personajes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formcrear', [
        'model' => $model,
        'modelUsuario' => $modelUsuario,
        'modelArmadura' => $modelArmadura,
        'modelRaza' => $modelRaza,
        'modelTrasfondo' => $modelTrasfondo,
    ]) ?>

</div>

views/personajes/personajes.php
<?php
    use yii\helpers\Html;
    use yii\helpers\HtmlPurifier;
    use yii\widgets\ListView;
    use yii\grid\GridView;
    
    $this->title = 'Personajes';
    $this->params['breadcrumbs'][] = $this->title;
?>
<?php if(Yii::$app->user->isGuest): ?>
    <div class="well well-lg"><h2 style="text-align: center">
        <?= Html::img('@web/images/personaje.png', ['class' => 'iconosheader'], ['alt' => 'personaje']); ?> 
            Personajes
        <?= Html::img('@web/images/personaje.png', ['class' => 'iconosheader'], ['alt' => 'personaje']); ?> 
        </h2>
    </div>
    <p>
        
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Filtrar
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><?= Html::a('Recomendados', ['personajes/personajesrecomendados']) ?></li>
              <li><?= Html::a('No Recomendados', ['personajes/personajesnorecomendados']) ?></li>
              <li role="separator" class="divider"></li>
              <li><?= Html::a('Todos', ['personajes/listapersonajes']) ?></li>
            </ul>
            <?= Html::a('Añadir personaje', ['personajes/createpersonajepasos'], ['class' => 'btn btn-default']) ?>
        </div>
        
    </p>
     
    <div class="view">

        <?= ListView::widget([
                   'dataProvider' => $dataProvider,
                   'itemView' => '_personajes',
                   'layout' => "\n{pager}\n{items}",
                ]);
         ?>       
    </div>

<?php else: ?>
    
    <div class="personajes-index">

        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('Añadir personaje', ['personajes/createpersonajepasos'], ['class' => 'btn btn-default']) ?>
            <?= Html::a('Objetos de los personajes', ['objetosdelpersonaje/index'], ['class' => 'btn btn-info']) ?>
            <?= Html::a('Armas de los personajes', ['armaspersonaje/index'], ['class' => 'btn btn-info']) ?>
            <?= Html::a('Clases de los personajes', ['clasesdelospersonajes/index'], ['class' => 'btn btn-info']) ?>
            <?= Html::a('Idiomas de los personajes', ['idiomaspersonaje/index'], ['class' => 'btn btn-info']) ?>
            <?= Html::a('Dotes de los personajes', ['dotesdelospersonajes/index'], ['class' => 'btn btn-info']) ?>
        </p>
        <p> 
            <?= Html::a('Lista de hechizos de los personajes', ['magiaspersonajes/index'], ['class' => 'btn btn-info']) ?>
        </p>

        
        <h2>Básico</h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\ActionColumn'],
                'nombre',
                [
                    'attribute' => 'recomendado',
                    'label'=>'¿Recomendado?',
                    'format'=>'raw',
                    'value' => function($model) { return $model->recomendado == 0 ? 'No' : 'Sí';},
                ],
                [
                    'attribute' => 'id_usuario',
                    'value' => 'usuario.nombre'
                 ],
                [
                    'attribute' => 'id_armadura',
                    'value' => 'armadura.nombre'
                 ],
                [
                    'attribute' => 'id_raza',
                    'value' => 'raza.nombre'
                 ],
                'ca',
                'descripción:ntext',
                [

                    'attribute' => 'imagen',

                    'format' => 'html',

                    'label' => 'Imagen',

                    'value' => function ($data) {

                        return Html::img($data['imagen'],

                            ['width' => '100px']);

                    },

                ],                                           
                'nivel',
                'percepción_pasiva',
                
            ],
        ]); ?>
        <h2> Trasfondo </h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',
                [
                    'attribute' => 'vivo',
                    'label'=>'¿Vivo?',
                    'format'=>'raw',
                    'value' => function($model) { return $model->recomendado == 0 ? 'No' : 'Sí';},
                ],
                'descripción:ntext',
                'biografia:ntext',
                'edad',
                [
                    'attribute' => 'id_trasfondo',
                    'value' => 'trasfondo.nombre'
                 ],
                ],
                ]);
                ?>
        <h2> Estadísticas </h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',
                'fuerza',
                'destreza',
                'constitucion',
                'inteligencia',
                'sabiduria',
                'carisma',
                ],
                ]);
                ?>
        <h2> Modificadores de las estadísticas </h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',
                'modfuerza',
                'moddestreza',
                'modconstitucion',
                'modinteligencia',
                'modsabiduria',
                'modcarisma',
                ],
                ]);
                ?>
        <h2> Salvaciones </h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',              
                'salvfuerza',
                'salvdestreza',
                'salvconstitucion',
                'salvinteligencia',
                'salvsabiduria',
                'salvcarisma',
                ],
                ]);
                ?>
        <h2> Habilidades</h2>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',
                'acrobacias',
                'atletismo',
                'conoarcano',
                'engaño',
                'historia',
                'interpretacion',
                'intimidacion',
                'investigacion',
                ],
                ]);
                ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                'nombre',
                'juego_de_manos',
                'medicina',
                'naturaleza',
                'percepcion',
                'perspicacia',
                'persuasión',
                'religion',
                'sigilo',
                'supervivencia',
                'trato_animales',
                ],
                ]);
                ?>
    </div>
    
<?php endif; ?>

views/personajes/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Personajes */

$this->title = 'Modificar personaje: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Personajes', 'url' => ['personajes/listapersonajes']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id_personaje]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="personajes-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formactualizar', [
        'model' => $model,
        'modelUsuario' => $modelUsuario,
        'modelArmadura' => $modelArmadura,
        'modelRaza' => $modelRaza,
        'modelTrasfondo' => $modelTrasfondo,
    ]) ?>

</div>