models/Magias.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "magias".
 *
 * @property int $id_magia
 * @property string $nombre
 * @property string|null $descripcion
 * @property string $nivel_conjuro
 * @property string $escuela
 * @property string $rango
 * @property string $tiempo_casteo
 * @property string $duración
 * @property string|null $concentracion_ritual
 *
 * @property Magiasclase[] $magiasclases
 * @property Clases[] $clases
 * @property Magiaspersonajes[] $magiaspersonajes
 * @property Personajes[] $personajes
 * @property Materialesmagias[] $materialesmagias
 * @property Recommagias[] $recommagias
 * @property Usuarios[] $usuarios
 */
class Magias extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'magias';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre', 'nivel_conjuro', 'escuela', 'rango', 'tiempo_casteo', 'duración'], 'required'],
            [['descripcion', 'nivel_conjuro', 'escuela', 'concentracion_ritual'], 'string'],
            [['nombre', 'rango', 'tiempo_casteo', 'duración'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_magia' => 'Id Magia',
            'nombre' => 'Nombre',
            'descripcion' => 'Descripcion',
            'nivel_conjuro' => 'Nivel Conjuro',
            'escuela' => 'Escuela',
            'rango' => 'Rango',
            'tiempo_casteo' => 'Tiempo Casteo',
            'duración' => 'Duración',
            'concentracion_ritual' => 'Concentracion Ritual',
        ];
    }

    /**
     * Gets query for [[Magiasclases]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMagiasclases()
    {
        return $this->hasMany(Magiasclase::className(), ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Clases]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getClases()
    {
        return $this->hasMany(Clases::className(), ['id_clase' => 'id_clase'])->viaTable('magiasclase', ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Magiaspersonajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMagiaspersonajes()
    {
        return $this->hasMany(Magiaspersonajes::className(), ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Personajes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPersonajes()
    {
        return $this->hasMany(Personajes::className(), ['id_personaje' => 'id_personaje'])->viaTable('magiaspersonajes', ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Materialesmagias]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMaterialesmagias()
    {
        return $this->hasMany(Materialesmagias::className(), ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Recommagias]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRecommagias()
    {
        return $this->hasMany(Recommagias::className(), ['id_magia' => 'id_magia']);
    }

    /**
     * Gets query for [[Usuarios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuarios()
    {
        return $this->hasMany(Usuarios::className(), ['id_usuario' => 'id_usuario'])->viaTable('recommagias', ['id_magia' => 'id_magia']);
    }
}

controllers/MagiasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Magias;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MagiasController implements the CRUD actions for Magias model.
 */
class MagiasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Magias models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Magias::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Magias model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Magias model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Magias();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_magia]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Magias model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_magia]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Magias model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['listamagias']);
    }

    /**
     * Finds the Magias model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Magias the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Magias::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionListamagias(){
        $dataProvider = new ActiveDataProvider([
            'query' => Magias::find(),
        ]);
        
        return $this->render('magias', [
            'dataProvider' => $dataProvider,
        ]);
    }
}

views/magias/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Magias */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="magias-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'nivel_conjuro')->dropDownList([ 'Truco' => 'Truco', 'Nivel 1' => 'Nivel 1', 'Nivel 2' => 'Nivel 2', 'Nivel 3' => 'Nivel 3', 'Nivel 4' => 'Nivel 4', 'Nivel 5' => 'Nivel 5', 'Nivel 6' => 'Nivel 6', 'Nivel 7' => 'Nivel 7', 'Nivel 8' => 'Nivel 8', 'Nivel 9' => 'Nivel 9', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'escuela')->dropDownList([ 'Evocación' => 'Evocación', 'Necromancia' => 'Necromancia', 'Adivinación' => 'Adivinación', 'Transmutación' => 'Transmutación', 'Encantamiento' => 'Encantamiento', 'Ilusión' => 'Ilusión', 'Conjuración' => 'Conjuración', 'Abjuración' => 'Abjuración', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'rango')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tiempo_casteo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'duración')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'concentracion_ritual')->dropDownList([ 'Concentración' => 'Concentración', 'Ritual' => 'Ritual', ], ['prompt' => '']) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/magias/_magias.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

?>

<div class="col-sm-4">
    <div class="thumbnail magias">
            <h5><?= implode(', ',ArrayHelper::getColumn($model->clases, 'nombre'))?></h5>
            <h3><u><?= $model->nombre?></u></h3>
            
            <h4><i> <?= $model->escuela ?>, <?= $model->nivel_conjuro ?></i></h3>
            <p> </p>
            <h4><b>Rango:</b> <?= $model->rango ?></h4>
            <h4><b>Componentes:</b> <?= implode(', ', ArrayHelper::getColumn($model->materialesmagias, 'material'))?></h4>
            <h4><b>Duración:</b> <?= $model->duración ?></h4>
            <?php if ($model->concentracion_ritual):?>
                <h4> <?= $model->concentracion_ritual ?> </h4>
            <?php endif; ?>
            
            <p class="invisible"> d</p>
            <h6 class="texto-magia"><?= $model->descripcion ?></h6>
        
    </div>
</div>

views/magias/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Magias */

$this->title = 'Añadir Magias';
$this->params['breadcrumbs'][] = ['label' => 'Magias', 'url' => ['magias/listamagias']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="magias-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/magias/magias.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ListView;
    use yii\grid\GridView;
    
    $this->title = 'Magias';
    $this->params['breadcrumbs'][] = $this->title;
?>
<?php if(Yii::$app->user->isGuest): ?>
<div class="view">
    
    <div class="well well-lg"><h2 style="text-align: center">
        <?= Html::img('@web/images/varita.png', ['class' => 'iconosheader'], ['alt' => 'espada']); ?> 
            Magias
        <?= Html::img('@web/images/varita.png', ['class' => 'iconosheader'], ['alt' => 'espada']); ?> 
        </h2>
    </div>
    
    <?= ListView::widget([
               'dataProvider' => $dataProvider,
               'itemView' => '_magias',
               'layout' => "\n{pager}\n{items}",
            ]);
     ?>       
</div>

<?php else: ?>

<div class="magias-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Añadir Magia/Hechizo/Conjuro', ['create'], ['class' => 'btn btn-default']) ?>
        <?= Html::a('Materiales de las magias', ['materialesmagias/index'], ['class' => 'btn btn-info']) ?>
        <?= Html::a('Magias que puede utilizar una clase', ['magiasclase/index'], ['class' => 'btn btn-info']) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
         
            ['class' => 'yii\grid\ActionColumn'],
            'nombre',
            'descripcion:ntext',
            'nivel_conjuro',
            'escuela',
            'rango',
            'tiempo_casteo',
            'duración',
            'concentracion_ritual',

        ],
    ]); ?>


</div>

<?php endif; ?>

views/magias/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Magias */

$this->title = 'Modificar Magia: ' . $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Magias', 'url' => ['magias/listamagias']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre, 'url' => ['view', 'id' => $model->id_magia]];
$this->params['breadcrumbs'][] = 'Modificar';
?>
<div class="magias-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/magias/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Magias */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Magias', 'url' => ['magias/listamagias']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="magias-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Modificar', ['update', 'id' => $model->id_magia], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id_magia], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estás seguro?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            
            'nombre',
            'descripcion:ntext',
            'nivel_conjuro',
            'escuela',
            'rango',
            'tiempo_casteo',
            'duración',
            'concentracion_ritual',
        ],
    ]) ?>

</div>